/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/_explore'
import { Route as ExploreIndexRouteImport } from './routes/_explore.index'
import { Route as CoinsCoinIdRouteImport } from './routes/coins.$coinId'

const ExploreRoute = ExploreRouteImport.update({
  id: '/_explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRoute,
} as any)
const CoinsCoinIdRoute = CoinsCoinIdRouteImport.update({
  id: '/coins/$coinId',
  path: '/coins/$coinId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ExploreIndexRoute
  '/coins/$coinId': typeof CoinsCoinIdRoute
}
export interface FileRoutesByTo {
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/': typeof ExploreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_explore': typeof ExploreRouteWithChildren
  '/coins/$coinId': typeof CoinsCoinIdRoute
  '/_explore/': typeof ExploreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coins/$coinId'
  fileRoutesByTo: FileRoutesByTo
  to: '/coins/$coinId' | '/'
  id: '__root__' | '/_explore' | '/coins/$coinId' | '/_explore/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ExploreRoute: typeof ExploreRouteWithChildren
  CoinsCoinIdRoute: typeof CoinsCoinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_explore': {
      id: '/_explore'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_explore/': {
      id: '/_explore/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/coins/$coinId': {
      id: '/coins/$coinId'
      path: '/coins/$coinId'
      fullPath: '/coins/$coinId'
      preLoaderRoute: typeof CoinsCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ExploreRouteChildren {
  ExploreIndexRoute: typeof ExploreIndexRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreIndexRoute: ExploreIndexRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ExploreRoute: ExploreRouteWithChildren,
  CoinsCoinIdRoute: CoinsCoinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
